vim.cmd([[ map q :q<CR> ]])
vim.cmd([[ nnoremap <C-s> :w<CR> ]])
vim.cmd([[ inoremap <C-s> <Esc>:w<CR>l ]])
vim.cmd([[ vnoremap <C-s> <Esc>:w<CR> ]])
vim.cmd([[ map <C-a> ggVG ]])
vim.cmd([[nnoremap <C-b> :NvimTreeToggle<CR>]])
vim.cmd([[nnoremap <C-p> :Telescope find_files<CR>]])
